export type PossibleNetworks = 'polkadot' | 'kusama' | 'westend' | 'rococo'

import { BrokerConstantsType, ConfigurationType } from '@poppyseed/lastic-sdk'

export type NetworkInfo = {
  [key: string]: {
    name: string
    tokenSymbol: string
    tokenDecimals: number
    apiUrl: string
    paraId: {
      [key: string]: {
        name: string
        description: string
        lease: number | null
      } // This tells TypeScript any string key returns a string value
    }
    constants: BrokerConstantsType | null // This values changes so little, that we can just store it here rather than having to read it from the state
    configuration: ConfigurationType | null
  }
}

export const network_list: NetworkInfo = {
  polkadot: {
    name: 'Polkadot',
    tokenSymbol: 'DOT',
    tokenDecimals: 10,
    apiUrl: 'https://polkadot.api.subscan.io/api',
    paraId: {
      '1000': { name: 'AssetHub', description: 'A hub for tokenized assets', lease: null },
      '1001': { name: 'Collectives', description: '', lease: null },
      '1002': { name: 'BridgeHub', description: '', lease: null },
      '1005': { name: 'Coretime', description: '', lease: null },
      '2000': { name: 'Acala', description: '', lease: null },
      '2002': { name: 'Clover', description: '', lease: null },
      '2004': { name: 'Moonbeam', description: '', lease: null },
      '2006': { name: 'Astar', description: '', lease: null },
      '2007': { name: 'Kapex', description: '', lease: null },
      '2008': { name: 'Crust', description: '', lease: null },
      '2012': { name: 'Parallel', description: '', lease: null },
      '2013': { name: 'Litentry', description: '', lease: null },
      '2019': { name: 'Composable Finance', description: '', lease: null },
      '2025': { name: 'SORA', description: '', lease: null },
      '2026': { name: 'Nodle', description: '', lease: null },
      '2027': { name: 'Coinversation', description: '', lease: null },
      '2030': { name: 'Bifrost', description: '', lease: null },
      '2031': { name: 'Centrifuge', description: '', lease: null },
      '2032': { name: 'Interlay', description: '', lease: null },
      '2034': { name: 'HydraDX', description: '', lease: null },
      '2035': { name: 'Phala Network', description: '', lease: null },
      '2037': { name: 'Unique Network', description: '', lease: null },
      '2039': { name: 'Integritee Network', description: '', lease: null },
      '2040': { name: 'Polkadex', description: '', lease: null },
      '2043': { name: 'NeuroWeb', description: '', lease: null },
      '2046': { name: 'Darwinia', description: '', lease: null },
      '2048': { name: 'Bitgreen', description: '', lease: null },
      '2051': { name: 'Ajuna Network', description: '', lease: null },
      '2053': { name: 'OmniBTC', description: '', lease: null },
      '2056': { name: 'Aventus', description: '', lease: null },
      '2058': { name: 'Watr Network', description: '', lease: null },
      '2086': { name: 'KILT Spiritnet', description: '', lease: null },
      '2090': { name: 'OAK Network', description: '', lease: null },
      '2091': { name: 'Frequency', description: '', lease: null },
      '2092': { name: 'Zeitgeist', description: '', lease: null },
      '2093': { name: 'Hashed Network', description: '', lease: null },
      '2094': { name: 'Pendulum', description: '', lease: null },
      '2101': { name: 'Subsocial', description: '', lease: null },
      '2104': { name: 'Manta', description: '', lease: null },
      '3333': { name: 't3rn', description: '', lease: null },
      '3338': { name: 'peaq', description: '', lease: null },
      '3340': { name: 'InvArch', description: '', lease: null },
      '3344': { name: 'Polimec', description: '', lease: null },
      '3345': { name: 'Energy Web X', description: '', lease: null },
      '3346': { name: 'Continuum', description: '', lease: null },
      '3354': { name: 'Logion', description: '', lease: null },
      '3369': { name: 'Mythos', description: '', lease: null },
      '3360': { name: 'NeuroWeb', description: '', lease: null },
      '3366': { name: 'Unknown', description: '', lease: null },
      '3367': { name: 'Hyperbridge (Nexus)', description: '', lease: null },
      '2011': { name: 'Equilibrium', description: '', lease: null },
      '2017': { name: 'SubGame Gamma', description: '', lease: null },
      '2018': { name: 'SubDAO', description: '', lease: null },
      '2021': { name: 'Efinity', description: '', lease: null },
      '2028': { name: 'Ares Odyssey', description: '', lease: null },
      '2038': { name: 'Geminis', description: '', lease: null },
      '2052': { name: 'Kylin', description: '', lease: null },
      '3334': { name: 'Moonsama', description: '', lease: null },
      '3359': { name: 'Integritee Network', description: '', lease: null },
      '3363': { name: 'Polkadex', description: '', lease: null },
    },
    constants: null,
    configuration: null,
  },
  kusama: {
    name: 'Kusama',
    tokenSymbol: 'KSM',
    tokenDecimals: 12,
    apiUrl: 'https://kusama.api.subscan.io/api',
    paraId: {
      '1000': {
        name: 'AssetHub',
        description: 'A hub for managing and trading digital assets.',
        lease: 24507199,
      },
      '1001': {
        name: 'Encointer Network',
        description: 'A network focused on local community currencies and social recognition.',
        lease: 25716799,
      },
      '1002': {
        name: 'BridgeHub',
        description: 'A bridging solution for connecting different blockchain networks.',
        lease: 25716799,
      },
      '1005': {
        name: 'Coretime',
        description: 'A decentralized time-stamping and verification network.',
        lease: 27329599,
      },
      '2000': {
        name: 'Karura',
        description: 'A DeFi hub and stablecoin platform on Kusama.',
        lease: 27329599,
      },
      '2001': {
        name: 'Bifrost',
        description: 'A staking liquidity and derivatives platform.',
        lease: 24507199,
      },
      '2004': {
        name: 'Khala Network',
        description: 'A privacy-focused cloud computing network.',
        lease: 26926399,
      },
      '2007': {
        name: 'Shiden',
        description: 'A smart contract platform supporting multiple blockchains.',
        lease: 25716799,
      },
      '2011': {
        name: 'SORA',
        description: 'A decentralized economic system for managing digital assets and DeFi.',
        lease: 26119999,
      },
      '2012': {
        name: 'Crust Shadow',
        description: 'A decentralized storage network providing cloud services.',
        lease: 24910399,
      },
      '2023': {
        name: 'Moonriver',
        description: 'A smart contract platform compatible with Ethereum, running on Kusama.',
        lease: 24910399,
      },
      '2024': {
        name: 'Genshiro',
        description: 'A DeFi platform offering various financial instruments.',
        lease: 24910399,
      },
      '2048': {
        name: 'Robonomics',
        description: 'An IoT and robotics integration platform.',
        lease: 24507199,
      },
      '2084': { name: 'Calamari', description: 'A privacy-focused DeFi network.', lease: 27329599 },
      '2085': {
        name: 'Parallel Heiko',
        description: 'A DeFi platform offering money markets and staking derivatives.',
        lease: 23700799,
      },
      '2087': {
        name: 'Picasso',
        description: 'A parachain focused on providing DeFi infrastructure and tools.',
        lease: 27329599,
      },
      '2090': {
        name: 'Basilisk',
        description: 'A liquidity bootstrapping platform for new crypto assets.',
        lease: 27329599,
      },
      '2095': {
        name: 'QUARTZ by UNIQUE',
        description: 'An NFT platform providing customization and marketplace functionalities.',
        lease: 26926399,
      },
      '2096': {
        name: 'Pioneer',
        description: 'A testing ground for new blockchain technologies.',
        lease: 26926399,
      },
      '2105': {
        name: 'Crab',
        description: 'A canary network for the Darwinia blockchain.',
        lease: 26119999,
      },
      '2106': {
        name: 'Litmus',
        description: 'A test network for the Litentry identity aggregation protocol.',
        lease: 26119999,
      },
      '2110': {
        name: 'Mangata',
        description: 'A decentralized exchange offering frictionless trading.',
        lease: 25716799,
      },
      '2113': {
        name: 'Kabocha',
        description: 'A project incubator and community-driven network.',
        lease: 26926399,
      },
      '2114': {
        name: 'Turing Network',
        description: 'A smart contract platform for automated business logic.',
        lease: 25716799,
      },
      '2119': {
        name: 'Bajun Network',
        description: 'A blockchain designed for gaming and digital collectibles.',
        lease: 27329599,
      },
      '2121': {
        name: 'Imbue Network',
        description: 'A crowdfunding platform for decentralized projects.',
        lease: 26926399,
      },
      '2123': {
        name: 'GM',
        description: 'A platform for governance and community engagement.',
        lease: 23700799,
      },
      '2125': {
        name: 'InvArch Tinkernet',
        description: 'A decentralized innovation network for collaborative projects.',
        lease: 23700799,
      },
      '2222': {
        name: 'DAO IPCI',
        description: 'A decentralized autonomous organization for environmental projects.',
        lease: 24507199,
      },
      '2236': {
        name: 'subzero',
        description: 'A network focused on secure and scalable cold storage solutions.',
        lease: 25716799,
      },
      '2239': {
        name: 'Acurast Canary',
        description: 'A test network for decentralized oracle services.',
        lease: 26926399,
      },
      '2241': {
        name: 'Krest',
        description: 'A blockchain platform for decentralized finance and applications.',
        lease: 26119999,
      },
      '2274': {
        name: 'Quantum Portal Network',
        description: 'A platform for cross-chain quantum computing solutions.',
        lease: 23700799,
      },
      '2281': {
        name: 'Kreivo - By Virto',
        description: 'A network for decentralized e-commerce solutions.',
        lease: 24507199,
      },
      '3334': {
        name: 't1rn',
        description: 'A blockchain network providing privacy and security features.',
        lease: 24910399,
      },
      '3336': {
        name: 'K-Laos',
        description: 'A decentralized network focused on supply chain transparency.',
        lease: 25716799,
      },
      '3339': {
        name: 'Curio',
        description: 'A platform for creating and managing digital art and collectibles.',
        lease: 26119999,
      },
      '3340': {
        name: 'Hyperbridge (Messier)',
        description: 'A cross-chain bridge facilitating interoperability between blockchains.',
        lease: 26119999,
      },
      '3344': {
        name: 'Xode',
        description: 'A decentralized autonomous organization for software development.',
        lease: 27329599,
      },
      '3345': {
        name: 'Yerba Network',
        description: 'A platform for sustainable agriculture and environmental projects.',
        lease: 26119999,
      },
      '2008': {
        name: 'Mars',
        description: 'A DeFi platform focused on yield farming and liquidity provision.',
        lease: null,
      },
      '2016': {
        name: 'Sakura',
        description: 'A testing and development network for the Clover finance ecosystem.',
        lease: null,
      },
      '2018': {
        name: 'SubGame Gamma',
        description: 'A blockchain gaming platform offering various play-to-earn opportunities.',
        lease: null,
      },
      '2019': {
        name: 'Kpron',
        description: 'A platform for decentralized finance and asset management.',
        lease: null,
      },
      '2078': {
        name: 'TrustBase',
        description: 'A protocol for decentralized identity and trust management.',
        lease: null,
      },
      '2080': {
        name: 'Loom Network',
        description: 'A layer 2 scaling solution for Ethereum and other blockchains.',
        lease: null,
      },
      '2094': {
        name: 'Unorthodox',
        description: 'A network for unconventional blockchain applications and experiments.',
        lease: null,
      },
      '2100': {
        name: 'SubsocialX',
        description: 'A decentralized social media platform.',
        lease: null,
      },
      '2102': {
        name: 'Pichiu',
        description: 'A blockchain network for small and medium enterprises.',
        lease: null,
      },
      '2107': {
        name: 'KICO',
        description: 'A decentralized finance platform for cross-chain transactions.',
        lease: null,
      },
      '2115': {
        name: 'Dora Factory',
        description: 'A decentralized governance and development platform.',
        lease: null,
      },
      '2116': {
        name: 'Tanganika',
        description: 'A blockchain platform for supply chain and logistics management.',
        lease: null,
      },
      '2126': {
        name: 'Parallel Heiko 2',
        description: 'An extension of the Parallel Heiko network for further DeFi applications.',
        lease: null,
      },
      '2129': {
        name: 'SNOW Network',
        description: 'A blockchain platform for decentralized finance and asset tokenization.',
        lease: null,
      },
      '2225': {
        name: 'Crust Shadow 2',
        description: 'An additional network for the Crust decentralized storage ecosystem.',
        lease: null,
      },
      '2226': {
        name: 'Genshiro crowdloan 2',
        description: 'A secondary crowdloan network for the Genshiro DeFi platform.',
        lease: null,
      },
      '2240': {
        name: 'Robonomics 2',
        description:
          'An additional network for the Robonomics IoT and robotics integration platform.',
        lease: null,
      },
    },
    constants: {
      maxLeasedCores: 50,
      maxReservedCores: 10,
      palletId: '0x70792f62726f6b65',
      timeslicePeriod: 80,
    },
    configuration: {
      advanceNotice: 10,
      interludeLength: 50400,
      leadinLength: 50400,
      regionLength: 5040,
      idealBulkProportion: 100,
      limitCoresOffered: null,
      renewalBump: 3,
      contributionTimeout: 5040,
    },
  },
  westend: {
    name: 'Westend',
    tokenSymbol: 'WST',
    tokenDecimals: 12,
    apiUrl: 'https://westend.api.subscan.io/api',
    paraId: {
      '1000': { name: 'assethub-westend', description: '', lease: null },
      '1001': { name: 'collectives', description: '', lease: null },
      '1002': { name: 'bridgehub-westend', description: '', lease: null },
      '1004': { name: 'people', description: '', lease: null },
      '1005': { name: 'coretime-westend', description: '', lease: null },
      '2002': { name: 'Moonshadow', description: '', lease: null },
      '2005': { name: 'Wendala', description: '', lease: null },
      '2013': { name: 'Whala', description: '', lease: null },
      '2081': { name: 'Integritee Network', description: '', lease: null },
      '2086': { name: 'Charcoal', description: '', lease: null },
      '2094': { name: 'Interlay', description: '', lease: null },
      '2112': { name: 'Pichiu', description: '', lease: null },
    },
    constants: {
      maxLeasedCores: 10,
      maxReservedCores: 10,
      palletId: '0x70792f62726f6b65',
      timeslicePeriod: 80,
    },
    configuration: {
      advanceNotice: 10,
      interludeLength: 7200,
      leadinLength: 21600,
      regionLength: 1260,
      idealBulkProportion: 40,
      limitCoresOffered: null,
      renewalBump: 0.35,
      contributionTimeout: 1260,
    },
  },
  rococo: {
    name: 'Rococo',
    tokenSymbol: 'ROC',
    tokenDecimals: 12,
    apiUrl: 'https://rococo.api.subscan.io/api',
    paraId: {
      '1000': { name: 'AssetHub', description: '', lease: 14587200 },
      '1003': { name: 'Encointer Lietaer', description: '', lease: 10555200 },
      '1004': { name: 'People', description: '', lease: 14025600 },
      '1005': { name: 'Coretime', description: '', lease: 13363200 },
      '1013': { name: 'Bridgehub', description: '', lease: 14529600 },
      '1836': { name: 'Trappist', description: '', lease: 11145600 },
      '2004': { name: 'Rhala Testnet', description: '', lease: 10972800 },
      '2007': { name: 'Stagex', description: '', lease: 11188800 },
      '2026': { name: 'Nodle', description: '', lease: 10569600 },
      '2030': { name: 'Bifrost', description: '', lease: null },
      '2031': { name: 'Catalyst', description: '', lease: 10886400 },
      '2034': { name: 'HydraDX', description: '', lease: 13161600 },
      '2040': { name: 'Kaizen', description: '', lease: 11433600 },
      '2043': { name: 'NeuroWeb Testnet', description: '', lease: 10900800 },
      '2056': { name: 'Aventus', description: '', lease: 12960000 },
      '2058': { name: 'Watr Network', description: '', lease: 14385600 },
      '2090': { name: 'Basilisk', description: '', lease: 14400000 },
      '2093': { name: 'MD5 Network', description: '', lease: 10569600 },
      '2100': { name: 'SoonsocialX', description: '', lease: 10512000 },
      '2101': { name: 'Zeitgeist Battery Station', description: '', lease: 13348800 },
      '2105': { name: 'Pangolin2', description: '', lease: 14400000 },
      '2106': { name: 'Litentry', description: '', lease: 14400000 },
      '2110': { name: 'Mangata', description: '', lease: 10742400 },
      '2114': { name: 'Turing Network (Staging)', description: '', lease: 10800000 },
      '2119': { name: 'Bajun Network', description: '', lease: 13248000 },
      '2124': { name: 'Amplitude testnet (Foucoco)', description: '', lease: 11577600 },
      '2125': { name: 'Tinkernet', description: '', lease: 10886400 },
      '2239': { name: 'Acurast Testnet', description: '', lease: 10915200 },
      '3016': { name: 'Snowbridge Bridge Hub', description: '', lease: 11520000 },
      '3333': { name: 't0rn', description: '', lease: 13248000 },
      '3339': { name: 'Curio Testnet', description: '', lease: 13737600 },
      '3345': { name: 'REX', description: '', lease: 11908800 },
      '3369': { name: 'Muse network', description: '', lease: 14932800 },
      '3416': { name: 'Snowbridge Asset Hub', description: '', lease: 11289600 },
      '4044': { name: 'Frequency', description: '', lease: 13521600 },
      '4292': { name: 'Yerba Network', description: '', lease: 12585600 },
      '4343': { name: 'Giedi', description: '', lease: 14140800 },
      '4374': { name: 'Hyperbridge (Gargantua)', description: '', lease: 12470400 },
      '1002': { name: 'Contracts', description: '', lease: null },
      '2011': { name: 'SORA', description: '', lease: null },
      '2012': { name: 'Crust Testnet', description: '', lease: null },
      '2021': { name: 'Rocfinity', description: '', lease: null },
      '2024': { name: 'Genshiro Testnet', description: '', lease: null },
      '2048': { name: 'Robonomics', description: '', lease: null },
      '2084': { name: 'Dolphin', description: '', lease: null },
      '2086': { name: 'RILT', description: '', lease: null },
      '2087': { name: 'Picasso Testnet', description: '', lease: null },
      '2095': { name: 'Ethos', description: '', lease: null },
      '2113': { name: 'Kabocha (kabsoup)', description: '', lease: null },
      '2116': { name: 'Spreehafen', description: '', lease: null },
      '2121': { name: 'Imbue Network', description: '', lease: null },
      '3003': { name: 'Virto', description: '', lease: null },
      '3015': { name: 'Arctic', description: '', lease: null },
      '3025': { name: 'Helixstreet', description: '', lease: null },
      '4023': { name: 'OLI', description: '', lease: null },
      '4040': { name: 'Subzero', description: '', lease: null },
      '4094': { name: 'Confti', description: '', lease: null },
      '4168': { name: 'Unit Network', description: '', lease: null },
      '4222': { name: 'Idiyanale Network', description: '', lease: null },
      '4227': { name: 'GIANT Protocol', description: '', lease: null },
      '4253': { name: 'Societal', description: '', lease: null },
      '4354': { name: 'OpenZeppelin Runtime Template', description: '', lease: null },
      '20048': { name: 'Bitgreen', description: '', lease: null },
    },
    constants: {
      maxLeasedCores: 50,
      maxReservedCores: 10,
      palletId: '0x70792f62726f6b65',
      timeslicePeriod: 80,
    },
    configuration: {
      advanceNotice: 10,
      interludeLength: 7200,
      leadinLength: 21600,
      regionLength: 1260,
      idealBulkProportion: 40,
      limitCoresOffered: null,
      renewalBump: 0.35,
      contributionTimeout: 1260,
    },
  },
}
